/*
* Author: Jesse Van Schothorst
* File: affirmations.js
* Breif: just for the affirmation page since I want to have a pretty long list
*        lots of this was just AI generated for the purpose of time
*/

export const affirmations = [
    "You are cool",
    "You are Majestic",
    "You are amazing",
    "You are loved",
    "You are talented",
    "You are capable of achieving anything you set your mind to.",
    "You radiate confidence and grace.",
    "You are deserving of love and happiness.",
    "You are worthy of all the good things life has to offer.",
    "You possess the strength to overcome any challenge.",
    "You are making a positive impact on the world around you.",
    "You are surrounded by abundance and prosperity.",
    "You are courageous and fearless in the face of adversity.",
    "You are enough just as you are.",
    "You are resilient and can bounce back from setbacks.",
    "You attract positivity and success into your life.",
    "You are surrounded by loving and supportive people.",
    "You are filled with boundless creativity and imagination.",
    "You are a magnet for opportunities and blessings.",
    "You are constantly growing and evolving into the best version of yourself.",
    "You are a beacon of light and inspiration to others.",
    "You are blessed with abundant energy and vitality.",
    "You are worthy of respect and admiration.",
    "You are beautiful inside and out.",
    "You are at peace with who you are and where you are headed.",
    "You are on the path to greatness.",
    "You are unstoppable and nothing can hold you back.",
    "You are the architect of your own destiny.",
    "You are a warrior, and you will emerge victorious.",
    "You are braver than you believe, stronger than you seem, and smarter than you think.",
    "You are surrounded by infinite possibilities.",
    "You are a source of inspiration and motivation to others.",
    "You are aligned with the universe and everything is falling into place.",
    "You are a magnet for miracles and blessings.",
    "You are worthy of all the good things life has to offer.",
    "You are deserving of success, happiness, and fulfillment.",
    "You are loved, cherished, and appreciated.",
    "You are a beacon of positivity and light.",
    "You are capable of achieving greatness.",
    "You are deserving of all the love and happiness in the world.",
    "You are courageous, bold, and fearless.",
    "You are surrounded by love, joy, and abundance.",
    "You are worthy of respect, admiration, and recognition.",
    "You are a magnet for success, prosperity, and abundance.",
    "You are capable of overcoming any obstacle.",
    "You are worthy of love, respect, and happiness.",
    "You are powerful beyond measure.",
    "You are worthy of all the blessings life has to offer.",
    "You are filled with love, light, and positivity.",
    "You are deserving of all the good things life has to offer.",
    "You are surrounded by love, joy, and abundance.",
    "You are worthy of respect, admiration, and recognition.",
    "You are a magnet for success, prosperity, and abundance.",
    "You are capable of overcoming any obstacle.",
    "You are worthy of love, respect, and happiness.",
    "You are powerful beyond measure.",
    "You are worthy of all the blessings life has to offer.",
    "You are filled with love, light, and positivity.",
];

